build: false

environment:
  matrix:
    - PYTHON: "C:\\Miniconda3-x64"
      PYTHON_VERSION: "3.5.x"
      PYTHON_ARCH: "32"
      NUMPY_VERSION: "1.13.1"
      SCIPY_VERSION: "0.19.1"
      SKLEARN_VERSION: "0.19.1"

    - PYTHON: "C:\\Miniconda3-x64"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "64"
      NUMPY_VERSION: "*"
      SCIPY_VERSION: "*"
      SKLEARN_VERSION: "*"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PYTHON%\\Library\\bin;%PATH%"
  - "conda install --yes -c conda-forge pip numpy==%NUMPY_VERSION% scipy==%SCIPY_VERSION% scikit-learn==%SKLEARN_VERSION%"
  - pip install codecov nose pytest pytest-cov
  - pip install .

test_script:
  - mkdir for_test
  - cd for_test
  - pytest -v --cov=template --pyargs template

after_test:
  - cp .coverage %APPVEYOR_BUILD_FOLDER%
  - cd %APPVEYOR_BUILD_FOLDER%
  - codecov
